name: rapidfuzz
description: "A dart port of the rapidfuzz library, for fuzzy-matching strings, and calculating the edit distance between strings."
version: 0.1.1
homepage: https://github.com/SphericalKat/rapidfuzz-flutter
license: MIT

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.19.1
dev_dependencies: 
  test: ^1.24.3
  lints: ^5.1.1
  analyzer: ^7.0.0